### PR TITLE
fix: improved image quality on the home page

### LINKED ISSUE #31: QA - Upscale images
Issue:
Very blurry image due to stretching, possible to upscale?
image

### PR DESCRIPTION
**Pull request by maeEsp**

### CODE REVIEW

File: src/components/ui/Article.tsx [hunk 1]
```diff
@@ -78,7 +78,7 @@ export default function Component({
           fill
           sizes="(max-width: 768px) 100vw, 50vw"
           className="object-cover"
-          priority
+          unoptimized
```
Comment (Miraii133) [inline src/components/ui/Article.tsx:81]: I genuinely did not know the unoptimized property existed. Great work!
